# Generated by Django 3.1.7 on 2021-03-26 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Hotel')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location of Hotel')),
                ('zip_code', models.IntegerField(blank=True, null=True, verbose_name='ZIP Code')),
                ('description', models.TextField(blank='', default=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of category')),
                ('max_guest', models.IntegerField(default=2, verbose_name='Max number of guests')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Description of Category')),
            ],
            options={
                'verbose_name': 'RoomCategory',
                'verbose_name_plural': 'RoomCategories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Number of room')),
                ('is_free', models.BooleanField(default=True, verbose_name='Check that room is free')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.hotel')),
                ('room_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotel.roomcategory')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='GUID of Reservation')),
                ('start_date', models.DateField(blank=True, verbose_name='Start date of reservation')),
                ('end_date', models.DateField(blank=True, verbose_name='End date of reservation')),
                ('guests_number', models.IntegerField(verbose_name='Number of guests')),
                ('customer', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('guid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='GUID of Payment')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Date of payment')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Status of payment')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='Amount of reservation')),
                ('customer', models.ForeignKey(help_text='', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('reservation', models.OneToOneField(help_text='Id of reservation for payment', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='hotel.reservation', verbose_name='reservation_id')),
            ],
        ),
    ]
